---
- hosts: mindhub-testers
  user: vagrant
  sudo: True
  vars:
    password: $1$pHvFX74N$fWbZdxyb1zxIXTQcVn7Kp0

  tasks:
    - name: update yum
      action: command /usr/bin/yum -y update

    - name: install web server packages
      action: yum pkg=$item state=installed
      with_items:
        - mysql-server
        - git
        - httpd

    - name: write httpd.conf
      action: template src=templates/httpd.conf dest=/etc/httpd/conf/httpd.conf

    - name: make deploy group
      group: name=deploy state=present

    - name: make deploy user
      user: name=deploy generate_ssh_key=yes group=deploy password=$password
